name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Backend install
        working-directory: backend
        run: npm ci

      - name: Prisma generate (backend)
        working-directory: backend
        run: npx prisma generate

      - name: Frontend install
        working-directory: frontend
        run: npm ci

      - name: Backend typecheck
        working-directory: backend
        run: npx --yes typescript@^5 tsc --noEmit

      - name: Frontend typecheck
        working-directory: frontend
        run: npx tsc --noEmit

      - name: Frontend lint
        working-directory: frontend
        run: npm run lint -- --no-inline-config --max-warnings=0 || true

      - name: Backend build
        working-directory: backend
        run: |
          npx --yes typescript@^5 tsc
